# Demo 10 - Distance Functions and Comparing Entities

In this notebook we do a few things with the [NBA Salary Dataset](https://github.com/joshrosson/NBASalaryPredictions) to illustrate working with relationships between variables. Specifically we'll look at distances between *observations* in this dataset and see what we can learn!

In [5]:
# clone the course repository, change to right directory, and import libraries.
%cd /content
!git clone https://github.com/nmattei/cmps6790.git
%cd /content/cmps6790/_demos

/content
fatal: destination path 'cmps6790' already exists and is not an empty directory.
/content/cmps6790/_demos

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
# Make the fonts a little bigger in our graphs.
font = {'size'   : 20}
plt.rc('font', **font)
plt.rcParams['mathtext.fontset'] = 'cm'
plt.rcParams['pdf.fonttype'] = 42
# Supress scientific notation
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Loading the Data and Down Selecting

First we'll load the data and focus on just a few attributes to make this more clear.

In [7]:
# Load the data
# Data from here: https://github.com/joshrosson/NBASalaryPredictions
df_nba = pd.read_csv("./data/nba_stats.csv")
display(df_nba.head(10))

# Always double check your Dtypes
df_nba.dtypes

,Season,Name,Salary,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1995,A.C. Green,6473000.00,SF,31,PHO,82,52,2687,311,...,0.73,194,475,669,127,55,31,114,146,916
1,1995,Aaron McKie,845000.00,SG,22,POR,45,20,827,116,...,0.69,35,94,129,89,36,16,39,97,293
2,1995,Aaron Swinson,NaN,SF,24,PHO,9,0,51,10,...,0.80,3,5,8,3,1,0,5,8,24
3,1995,Aaron Williams,NaN,PF,23,MIL,15,0,72,8,...,0.67,5,14,19,0,2,6,7,14,24
4,1995,Acie Earl,1040000.00,C,24,BOS,30,3,208,26,...,0.48,19,26,45,2,6,8,14,39,66
5,1995,Adam Keefe,1650000.00,SF,24,UTA,75,0,1270,172,...,0.68,135,192,327,30,36,25,62,141,461
6,1995,Adrian Caldwell,225000.00,PF,28,HOU,7,0,30,1,...,0.50,1,9,10,0,1,0,1,6,5
7,1995,Alaa Abdelnaby,NaN,PF,26,TOT,54,0,506,118,...,0.57,37,77,114,13,15,12,45,104,256
8,1995,Alaa Abdelnaby,NaN,PF,26,SAC,51,0,476,117,...,0.57,34,72,106,13,15,12,40,102,254
9,1995,Alaa Abdelnaby,NaN,PF,26,PHI,3,0,30,1,...,NaN,3,5,8,0,0,0,5,2,2

Season      int64
Name       object
Salary    float64
Pos        object
Age         int64
Tm         object
G           int64
GS          int64
MP          int64
FG          int64
FGA         int64
FG%       float64
3P          int64
3PA         int64
3P%       float64
2P          int64
2PA         int64
2P%       float64
FT          int64
FTA         int64
FT%       float64
ORB         int64
DRB         int64
TRB         int64
AST         int64
STL         int64
BLK         int64
TOV         int64
PF          int64
PTS         int64
dtype: object

Let's use all the years this time but only a subset of the stats.

In [8]:
# Why did I copy this time?
df_smallNBA = df_nba[["Name", "Salary", "Season", "Pos", "Age", "MP", "PTS","TRB", "AST"]].copy()
df_smallNBA.head(10)

              Name     Salary  Season Pos  Age    MP  PTS  TRB  AST
0       A.C. Green 6473000.00    1995  SF   31  2687  916  669  127
1      Aaron McKie  845000.00    1995  SG   22   827  293  129   89
2    Aaron Swinson        NaN    1995  SF   24    51   24    8    3
3   Aaron Williams        NaN    1995  PF   23    72   24   19    0
4        Acie Earl 1040000.00    1995   C   24   208   66   45    2
5       Adam Keefe 1650000.00    1995  SF   24  1270  461  327   30
6  Adrian Caldwell  225000.00    1995  PF   28    30    5   10    0
7   Alaa Abdelnaby        NaN    1995  PF   26   506  256  114   13
8   Alaa Abdelnaby        NaN    1995  PF   26   476  254  106   13
9   Alaa Abdelnaby        NaN    1995  PF   26    30    2    8    0

# Find the closest players!

In [10]:
# Get a smaller set, drop NA's
df_smallNBA.dropna(inplace=True)
df_smallNBA.reset_index(drop=True, inplace=True)
df_smallNBA.head(10)

                Name     Salary  Season Pos  Age    MP   PTS  TRB  AST
0         A.C. Green 6473000.00    1995  SF   31  2687   916  669  127
1        Aaron McKie  845000.00    1995  SG   22   827   293  129   89
2          Acie Earl 1040000.00    1995   C   24   208    66   45    2
3         Adam Keefe 1650000.00    1995  SF   24  1270   461  327   30
4    Adrian Caldwell  225000.00    1995  PF   28    30     5   10    0
5   Alonzo Mourning* 4560000.00    1995   C   24  2941  1643  761  111
6       Alton Lister  300000.00    1995   C   36   776   167  236   12
7        Andrew Lang 1964000.00    1995   C   28  2340   794  456   72
8  Anfernee Hardaway 5230000.00    1995  PG   23  2901  1613  336  551
9      Anthony Avent  950000.00    1995  PF   25  1066   258  293   41

Transform the categorical variables

In [11]:
# get dummies
df_ml = pd.get_dummies(df_smallNBA, columns=["Pos"], dtype=int)
display(df_ml.head(10))
len(df_ml)

,Name,Salary,Season,Age,MP,PTS,TRB,AST,Pos_C,Pos_C-PF,...,Pos_PG,Pos_PG-SF,Pos_PG-SG,Pos_SF,Pos_SF-PF,Pos_SF-SG,Pos_SG,Pos_SG-PF,Pos_SG-PG,Pos_SG-SF
0,A.C. Green,6473000.00,1995,31,2687,916,669,127,0,0,...,0,0,0,1,0,0,0,0,0,0
1,Aaron McKie,845000.00,1995,22,827,293,129,89,0,0,...,0,0,0,0,0,0,1,0,0,0
2,Acie Earl,1040000.00,1995,24,208,66,45,2,1,0,...,0,0,0,0,0,0,0,0,0,0
3,Adam Keefe,1650000.00,1995,24,1270,461,327,30,0,0,...,0,0,0,1,0,0,0,0,0,0
4,Adrian Caldwell,225000.00,1995,28,30,5,10,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Alonzo Mourning*,4560000.00,1995,24,2941,1643,761,111,1,0,...,0,0,0,0,0,0,0,0,0,0
6,Alton Lister,300000.00,1995,36,776,167,236,12,1,0,...,0,0,0,0,0,0,0,0,0,0
7,Andrew Lang,1964000.00,1995,28,2340,794,456,72,1,0,...,0,0,0,0,0,0,0,0,0,0
8,Anfernee Hardaway,5230000.00,1995,23,2901,1613,336,551,0,0,...,1,0,0,0,0,0,0,0,0,0
9,Anthony Avent,950000.00,1995,25,1066,258,293,41,0,0,...,0,0,0,0,0,0,0,0,0,0

9354

Drop the non-comparable variables

In [12]:
# drop name column and Salary (target) for ML
df_ml.drop(columns=["Name","Salary"],inplace=True)
df_ml.head(10)

,Season,Age,MP,PTS,TRB,AST,Pos_C,Pos_C-PF,Pos_PF,Pos_PF-C,...,Pos_PG,Pos_PG-SF,Pos_PG-SG,Pos_SF,Pos_SF-PF,Pos_SF-SG,Pos_SG,Pos_SG-PF,Pos_SG-PG,Pos_SG-SF
0,1995,31,2687,916,669,127,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,1995,22,827,293,129,89,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,1995,24,208,66,45,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1995,24,1270,461,327,30,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1995,28,30,5,10,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,1995,24,2941,1643,761,111,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1995,36,776,167,236,12,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1995,28,2340,794,456,72,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1995,23,2901,1613,336,551,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9,1995,25,1066,258,293,41,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

Let's calculate the euclidean distance by hand

In [14]:
# most straightforward, but inefficient
def euclidean(x,y):
    total = 0
    for feat in x.index:
        total+= pow(x[feat] - y[feat],2)
    return np.sqrt(total)

euclidean(df_ml.loc[0], df_ml.loc[1])

np.float64(2034.9093345896274)

In [15]:
# More efficient
def euclidean_v2(x,y):
   return np.sqrt(pow(x-y,2).sum())

euclidean_v2(df_ml.loc[0], df_ml.loc[1])

np.float64(2034.9093345896274)

Compute the Manhattan distance

In [16]:
def manhattan(x,y):
    return abs(x-y).sum()
manhattan(df_ml.loc[0], df_ml.loc[1])

np.int64(3072)

We're going to start using [SKLearn](https://scikit-learn.org/stable/modules/classes.html#sklearn-metrics-metrics) we'll get more into it as we go!

In [17]:
# Use SKLEARN to do some distances.
from sklearn.metrics import pairwise_distances

D = pairwise_distances(df_ml, metric="euclidean")
D.shape

(9354, 9354)

So what does this D matrix have inside of it?

In [18]:

D

array([[   0.        , 2034.90933459, 2696.84871656, ..., 1068.36463813,
         910.99560921, 1523.56621123],
       [2034.90933459,    0.        ,  670.31410548, ..., 1099.62948305,
        1296.76944751,  541.81731238],
       [2696.84871656,  670.31410548,    0.        , ..., 1756.20898529,
        1932.96249317, 1184.85146748],
       ...,
       [1068.36463813, 1099.62948305, 1756.20898529, ...,    0.        ,
         462.491081  ,  713.37437577],
       [ 910.99560921, 1296.76944751, 1932.96249317, ...,  462.491081  ,
           0.        ,  816.20034305],
       [1523.56621123,  541.81731238, 1184.85146748, ...,  713.37437577,
         816.20034305,    0.        ]])

In [19]:
D[1,0]

np.float64(2034.9093345896274)

Let's find the most similar player to Anthony Davis

In [20]:
# Find someone intersting...
df_smallNBA[(df_smallNBA['Name'] == 'Anthony Davis')]

               Name      Salary  Season Pos  Age    MP   PTS  TRB  AST
6995  Anthony Davis  5375760.00    2013  PF   19  1846   867  522   63
7406  Anthony Davis  5607240.00    2014  PF   20  2358  1394  673  105
7878  Anthony Davis  7070730.00    2015  PF   21  2455  1656  696  149
8416  Anthony Davis 22116750.00    2016   C   22  2164  1481  627  116
8892  Anthony Davis 23775506.00    2017   C   23  2708  2099  886  157

In [21]:
# So let's see who was the closest to Davis's 2016 Season
D[8416,:].argmin()

np.int64(8416)

In [22]:
# Wait... that's me... what went wrong here?
np.fill_diagonal(D,np.inf)

In [23]:
D[8416,:].argmin()

np.int64(6805)

In [24]:
df_smallNBA.loc[[6805]]

# 2012 Kevin love who dis? Explains why Lebron wanted that trade hunh?

            Name      Salary  Season Pos  Age    MP   PTS  TRB  AST
6805  Kevin Love 13668750.00    2012  PF   23  2145  1432  734  111

In [25]:
df_ml.loc[[8416,6805]]

,Season,Age,MP,PTS,TRB,AST,Pos_C,Pos_C-PF,Pos_PF,Pos_PF-C,...,Pos_PG,Pos_PG-SF,Pos_PG-SG,Pos_SF,Pos_SF-PF,Pos_SF-SG,Pos_SG,Pos_SG-PF,Pos_SG-PG,Pos_SG-SF
8416,2016,22,2164,1481,627,116,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6805,2012,23,2145,1432,734,111,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

Lots of different distances we could use [SKLearn Distance Functions](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.DistanceMetric.html)

In [26]:
# If we change the distance metric what happens?
D = pairwise_distances(df_ml, metric="hamming")
np.fill_diagonal(D, np.inf)
nearest = D[8416, :].argmin()
print(nearest)

6805

In [27]:
df_smallNBA.loc[[8416,nearest]]

               Name      Salary  Season Pos  Age    MP   PTS  TRB  AST
8416  Anthony Davis 22116750.00    2016   C   22  2164  1481  627  116
6805     Kevin Love 13668750.00    2012  PF   23  2145  1432  734  111

What if we standardarized our quant variables?

In [28]:
#identify quant vars
quant_vars = ["Season","Age","MP","PTS","TRB","AST"]

In [29]:
#standardize quant vars
df_ml_std = df_ml.copy()
df_ml_std[quant_vars] = (df_ml[quant_vars] - df_ml[quant_vars].mean())/df_ml[quant_vars].std()
df_ml_std.head()

,Season,Age,MP,PTS,TRB,AST,Pos_C,Pos_C-PF,Pos_PF,Pos_PF-C,...,Pos_PG,Pos_PG-SF,Pos_PG-SG,Pos_SF,Pos_SF-PF,Pos_SF-SG,Pos_SG,Pos_SG-PF,Pos_SG-PG,Pos_SG-SF
0,1995,1.00,1.57,0.84,2.26,0.08,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,1995,-1.15,-0.52,-0.51,-0.49,-0.21,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,1995,-0.67,-1.21,-1.00,-0.92,-0.86,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1995,-0.67,-0.02,-0.14,0.52,-0.65,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1995,0.29,-1.41,-1.13,-1.09,-0.87,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
D_std = pairwise_distances(df_ml_std, metric="euclidean")
np.fill_diagonal(D_std, np.inf)
nearest_std = D_std[8416,:].argmin()
nearest_raw = D[8416,:].argmin()
print(nearest_std, nearest_raw)

8544 6805

In [32]:
df_smallNBA.loc[[8416,nearest_std,nearest_raw]]

               Name      Salary  Season Pos  Age    MP   PTS  TRB  AST
8416  Anthony Davis 22116750.00    2016   C   22  2164  1481  627  116
8544    Greg Monroe 17100000.00    2016   C   25  2314  1210  696  178
6805     Kevin Love 13668750.00    2012  PF   23  2145  1432  734  111

In [33]:
df_ml_std.loc[[8416,nearest_std,nearest_raw]]

,Age,MP,PTS,TRB,AST,Pos_C,Pos_C-PF,Pos_PF,Pos_PF-C,Pos_PF-SF,...,Season_2008,Season_2009,Season_2010,Season_2011,Season_2012,Season_2013,Season_2014,Season_2015,Season_2016,Season_2017
8416,-1.15,0.98,2.06,2.05,-0.01,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8544,-0.43,1.15,1.48,2.40,0.46,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6805,-0.91,0.96,1.96,2.60,-0.04,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0