In [ ]:
# clone the course repository, change to right directory, and import libraries.
%cd /content
!git clone https://github.com/nmattei/cmps3160.git
%cd /content/cmps3160/_demos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
# Make the fonts a little bigger in our graphs.
font = {'size'   : 20}
plt.rc('font', **font)
plt.rcParams['mathtext.fontset'] = 'cm'
plt.rcParams['pdf.fonttype'] = 42

/content
Cloning into 'cmps3160'...
remote: Enumerating objects: 2500, done.
remote: Counting objects: 100% (488/488), done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 2500 (delta 417), reused 379 (delta 344), pack-reused 2012 (from 1)
Receiving objects: 100% (2500/2500), 55.45 MiB | 29.00 MiB/s, done.
Resolving deltas: 100% (1543/1543), done.
Updating files: 100% (160/160), done.
/content/cmps3160/_demos

## Joins in Pandas

Let's see a few [joins in Pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html) and how to execute them.

**Note:** We can also use the [merge command in pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) to joins as well.  We'll explore this more fully in the lab.  The key idea is that merge let's us pick columns to do the merge/join while join will always join on the index.

In [ ]:
# Initialize two dataframes
# Careful here! We have to set the index!
df1 = pd.DataFrame([(1, 'foo', 3),
                    (2, 'bar', 2),
                    (3, 'foo', 4),
                    (4, 'foo', 3)],
                  columns=['ID','A', 'B'])
df1.set_index('ID', inplace=True)
display(df1)

df2 = pd.DataFrame([(1, 1.2), (2, 2.5), (3, 2.3), (5, 8.0)],
                   columns=['ID','C'])
df2.set_index('ID', inplace=True)
display(df2)

      A  B
ID
1   foo  3
2   bar  2
3   foo  4
4   foo  3

      C
ID
1   1.2
2   2.5
3   2.3
5   8.0

To perform joins, we can use the `df1.join(df2,...)`. The calling dataframe (`df1`) will be the left table, while the passed in dataframe (`df1`) will be the right.


**Question:** What type of join do you think will be returned in the call below?

In [ ]:
# Default join
df1.join(df2)

      A  B    C
ID
1   foo  3  1.2
2   bar  2  2.5
3   foo  4  2.3
4   foo  3  NaN


We can also explicitly specify the type of join we wish it to perform using the `how` paramter. Below, we set `how='inner'` to perform an inner join.

In [ ]:
# Inner join
df1.join(df2, how='inner')

      A  B    C
ID
1   foo  3  1.2
2   bar  2  2.5
3   foo  4  2.3

We can perform each type of join this way by setting `how` to `inner`, `outer`, `left`, or `right`

In [ ]:
# Can do inner, outer, left, right.
df1.join(df2, how='right')

      A    B    C
ID
1   foo  3.0  1.2
2   bar  2.0  2.5
3   foo  4.0  2.3
5   NaN  NaN  8.0

**Question:** What column is pandas using to perform the `.join()`?

Let's see what happens if we want to join on a specific column. Here, we want to join the tables using the leftid and rightid columns.

In [ ]:
# create data frame one with an id column called leftID
df1 = pd.DataFrame([(1, 'foo', 3), (2, 'bar', 2), (3, 'foo', 4), (4, 'foo', 3)],
                  columns=['leftid','A', 'B'])
display(df1)

# create data frame two with an id column called rightID
df2 = pd.DataFrame([(1, 1.2), (2, 2.5), (3, 2.3), (5, 8.0)],
                   columns=['rightid','C'])

display(df2)

   leftid    A  B
0       1  foo  3
1       2  bar  2
2       3  foo  4
3       4  foo  3

   rightid    C
0        1  1.2
1        2  2.5
2        3  2.3
3        5  8.0

**Question:** If we want to perform an inner join using the `leftid` and `rightid` columns, what should the result look like?


Answer:

| id | A | B | C |
| ----- | ----- | ----- | ----- |
| 1 | foo | 3 | 1.2 |
| 2 | bar | 2 | 2.5 |
| 3 | foo | 4 | 2.3 |

 (`id` is the merged `leftid` & `rightid` columns)

Let's try an inner join and see if this is what we get.

In [ ]:
# Inner join
df1.join(df2, how='inner')

   leftid    A  B  rightid    C
0       1  foo  3        1  1.2
1       2  bar  2        2  2.5
2       3  foo  4        3  2.3
3       4  foo  3        5  8.0

**Question:** Is this what we wanted?


No, pandas simply joined on the index of each table.

We can tell pandas what variable we want to join on.

In [ ]:
# join on leftid
df1.join(df2, how='inner', on='leftid')

   leftid    A  B  rightid    C
0       1  foo  3        2  2.5
1       2  bar  2        3  2.3
2       3  foo  4        5  8.0

**Question:** Now, is this what we wanted?

While we can specify the column in the left table (the calling dataframe), it will still joint with the index of the right table. To complete the join correctly, we need to set `rightid` as the index of the right table (`df2`)

In [ ]:
#set index of df2
df2 = df2.set_index('rightid')

# inner join df1 to df2 on leftid
df1.join(df2, how='inner', on='leftid')

   leftid    A  B    C
0       1  foo  3  1.2
1       2  bar  2  2.5
2       3  foo  4  2.3

Now, we have the join we wanted. However, we can do this more easily using the `.merge()` function instead.


## Pandas Merge

Or we can skip all this foolishness by using the [pandas merge](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) command...

Let's recreate our two dataframes, each with an ID column.

In [ ]:
# create and display df1
df1 = pd.DataFrame([(1, 'foo', 3), (2, 'bar', 2), (3, 'foo', 4), (4, 'foo', 3)],
                  columns=['ID','A', 'B'])
display(df1)

# create and display df2
df2 = pd.DataFrame([(1, 1.2), (2, 2.5), (3, 2.3), (5, 8.0)],
                   columns=['ID','C'])
display(df2)

   ID    A  B
0   1  foo  3
1   2  bar  2
2   3  foo  4
3   4  foo  3

   ID    C
0   1  1.2
1   2  2.5
2   3  2.3
3   5  8.0

The `.merge(...)` function operates similar to the `.join(...)` function but with some additional helpful parameters. Let's start by looking at the default merge.

In [ ]:
# merge df1 and df2
df1.merge(df2)

   ID    A  B    C
0   1  foo  3  1.2
1   2  bar  2  2.5
2   3  foo  4  2.3

**Question:** What type of join was performed and on what column? How does this compare to the default `.join()`?

As we can see, similar to `.join()`, `.merge()` defaults to using the `index` to perform the merge. Unlike `.join()`, it performs an inner join by default.

This isn't the merge we wanted. Let's take a look at some helpful parameters for specifying the correct merge.

`.merge(...)` has two parameters that will be helpful for us: `left_on` and `right_on`. These allow us to direclty specify which columns in each table we would like to join on, in this case the `ID` column in each table.

In [ ]:
# join on the ID column of each table
df1.merge(df2, left_on="ID", right_on="ID")

   ID    A  B    C
0   1  foo  3  1.2
1   2  bar  2  2.5
2   3  foo  4  2.3

If we don't want an inner join, we can use the `how` parameter to specify the type of join. It has the same options as the `how` parameter in `.join()`.

In [ ]:
# perform a full outer join
df1.merge(df2, left_on="ID", right_on="ID", how='outer')

   ID    A    B    C
0   1  foo  3.0  1.2
1   2  bar  2.0  2.5
2   3  foo  4.0  2.3
3   4  foo  3.0  NaN
4   5  NaN  NaN  8.0

In [ ]:
# perform a left join
df1.merge(df2, left_on="ID", right_on="ID", how='left')

   ID    A  B    C
0   1  foo  3  1.2
1   2  bar  2  2.5
2   3  foo  4  2.3
3   4  foo  3  NaN

In [ ]:
# perform a right join
df1.merge(df2, left_on="ID", right_on="ID", how='right')

   ID    A    B    C
0   1  foo  3.0  1.2
1   2  bar  2.0  2.5
2   3  foo  4.0  2.3
3   5  NaN  NaN  8.0

Overall, `.merge()` allows us to more flexibly specify joins, making it our preferred function for joining dataframes.

# A crash course in SQL (in python) using SQLite

[SQLite](https://sqlite.org/) is a free and open-source library that implements a small, fast, and self-contained SQL database engine. Unlike most SQL databases, SQLite is serverless - it reads and writes directly to files on disk.


Helpful here is the [SQLite Cheat Sheet](https://www.sqlitetutorial.net/sqlite-cheat-sheet/) and [Python library](https://docs.python.org/3/library/sqlite3.html) documentation.

To start, we connect to a database using sqlite.

In [ ]:
import sqlite3

conn = sqlite3.connect("cmps3160.db")

The above function looks for an existing `cmps3160.db` file in the current directory. If it doesn't find one, it will create one.

To interact with this database, we can create the **cursor**.

The **cursor** is a temporary work area in system memory for manipulating SQL statements and return values.

In [ ]:
# create db cursor
cursor = conn.cursor()

To execute SQL statements, we can call `cursor.execute(""" some SQL statement """)`.

SQL (Structured Query Language) is a programming language used to store, retrieve, manipulate, and analyze data in relational databases.

A SQL query is a command that specifies what data to retrieve or manipulate in a database. They are intended to read like natural English.

Let's look at creating a table.

In [ ]:
# create a table for cats
cursor.execute('''
CREATE TABLE cats (
    cat_id INTEGER PRIMARY KEY,
    name TEXT
)''')

The capitalized words are SQL commands and keywords while the lowercase words reference the specific table.

Note, technically, the SQL commands do not need to be capitalized - SQL is not case sensitive. However, it is good pracitce to use this formatting for readability and clarity.

Let's add some data to our table!

In [ ]:
# Insert into the table
cursor.execute('''INSERT INTO cats VALUES (1, "Megabyte")''')
cursor.execute('''INSERT INTO cats VALUES (2, "Meowly Cyrus")''')
cursor.execute('''INSERT INTO cats VALUES (3, "Fuzz Aldrin")''')
cursor.execute('''INSERT INTO cats VALUES (4, "Chairman Meow")''')
cursor.execute('''INSERT INTO cats VALUES (5, "Anderson Pooper")''')
cursor.execute('''INSERT INTO cats VALUES (6, "Gigabyte")''')

After we make changes to our database, it is a good idea to periodically save those changes. We can do this by "commiting" them to the files on disk.

In [ ]:
# Commit will update the database on disk with a set of changes.
conn.commit()

We can select from our database as well using the syntax `SELECT [columns] FROM [table]`. To select all columns, we can use `*`.

In [ ]:
cursor.execute('''SELECT * FROM cats''')

This will return the result in the form of a cursor object. We can iterate over this object to get each returned row.

In [ ]:
# Iterate over the object we get back
for row in cursor.execute('''SELECT * FROM cats'''):
    print(row)

(1, 'Megabyte')
(2, 'Meowly Cyrus')
(3, 'Fuzz Aldrin')
(4, 'Chairman Meow')
(5, 'Anderson Pooper')
(6, 'Gigabyte')

We can also use Pandas to read a sql query and turn the result into a dataframe!

In [ ]:
# create a dataframe from the returned the selection
# we can specify what to do for the index here using "index_col"
pd.read_sql_query("SELECT * FROM cats", conn, index_col="cat_id")

                   name
cat_id
1              Megabyte
2          Meowly Cyrus
3           Fuzz Aldrin
4         Chairman Meow
5       Anderson Pooper
6              Gigabyte

We can also remove rows frmo the database.

In [ ]:
# delete cat 4
cursor.execute('''DELETE FROM cats WHERE cat_id == 4''')
conn.commit()
pd.read_sql_query("SELECT * FROM cats", conn, index_col="cat_id")

                   name
cat_id
1              Megabyte
2          Meowly Cyrus
3           Fuzz Aldrin
5       Anderson Pooper
6              Gigabyte

## Joins in SQL

Recall, a **join** operation merges two or more tables into a single realtion. We have four types of joins:
- Inner
- Left
- Right
- Full Outer

Join operations are done on columns that link tables together.

Let's make a table of vet visits for the cats and see how to perfom joins.

In [ ]:
# Create a table for vet visits
cursor.execute('''
CREATE TABLE visits (
    visit_id INTEGER PRIMARY KEY,
    date DATE,
    cat_id INTEGER,
    FOREIGN KEY(cat_id) REFERENCES cats(cat_id)
)''')

Now, let's add some data to this table.

In [ ]:
# add rows to the new table
cursor.execute('''INSERT INTO visits VALUES (1, "02-16-2017", 1)''')
cursor.execute('''INSERT INTO visits VALUES (2, "02-14-2017", 1)''')
cursor.execute('''INSERT INTO visits VALUES (5, "02-03-2017", 2)''')
cursor.execute('''INSERT INTO visits VALUES (3, "02-0`-2017", 4)''')

# commit our changes to the disk files
conn.commit()

Lets's check our table by reading it into Pandas.

In [ ]:
# select all from table and read into dataframe
pd.read_sql_query("SELECT * FROM visits", conn, index_col="visit_id")

                date  cat_id
visit_id
1         02-16-2017       1
2         02-14-2017       1
3         02-0`-2017       4
5         02-03-2017       2

### Inner joins:

#### Method 1: read tables to pandas and merge

In [ ]:
# select all cats into df_cats
df_cats = pd.read_sql_query('''SELECT * from cats''', conn)
display(df_cats)

#select all visits into df_visits
df_visits = pd.read_sql_query('''SELECT * from visits''', conn)
display(df_visits)

   cat_id             name
0       1         Megabyte
1       2     Meowly Cyrus
2       3      Fuzz Aldrin
3       5  Anderson Pooper
4       6         Gigabyte

   visit_id        date  cat_id
0         1  02-16-2017       1
1         2  02-14-2017       1
2         3  02-0`-2017       4
3         5  02-03-2017       2

In [ ]:
# merge df_cats and df_visits on cat_id
df_cats.merge(df_visits, how = "inner",
              left_on = "cat_id", right_on = "cat_id")

   cat_id          name  visit_id        date
0       1      Megabyte         1  02-16-2017
1       1      Megabyte         2  02-14-2017
2       2  Meowly Cyrus         5  02-03-2017

#### Method 2: join directly using SQL

We can join directly using SQL. To perform an **inner join**, we can do this by simply selecting from multiple tables and specifying a condition that relates them:

`SELECT [columns] FROM [tables] WHERE [condition that specifies how tables relate]`

In [ ]:
# perform an inner join between cats and visits
# use the cat_id column in each table
result = cursor.execute('''
               SELECT
                   *
               FROM
                   cats, visits
               WHERE
                   cats.cat_id == visits.cat_id
               ''')
for i in result:
    print(i)

(1, 'Megabyte', 1, '02-16-2017', 1)
(1, 'Megabyte', 2, '02-14-2017', 1)
(2, 'Meowly Cyrus', 5, '02-03-2017', 2)

### Other Joins

What if we want to perform a different type of join?

Again, we could read each table into pandas and use the merge function.

In [ ]:
# perfrom a left join
df_cats.merge(df_visits, how = "left",
              left_on = "cat_id", right_on = "cat_id")

   cat_id             name  visit_id        date
0       1         Megabyte       1.0  02-16-2017
1       1         Megabyte       2.0  02-14-2017
2       2     Meowly Cyrus       5.0  02-03-2017
3       3      Fuzz Aldrin       NaN         NaN
4       5  Anderson Pooper       NaN         NaN
5       6         Gigabyte       NaN         NaN

Using SQL, we have to sepcify that we want to `LEFT JOIN` with a second table.

In [ ]:
result = cursor.execute('''SELECT * FROM
                                cats
                           LEFT JOIN
                               visits
                           ON
                               cats.cat_id == visits.cat_id''')
for i in result:
    print(i)

(1, 'Megabyte', 2, '02-14-2017', 1)
(1, 'Megabyte', 1, '02-16-2017', 1)
(2, 'Meowly Cyrus', 5, '02-03-2017', 2)
(3, 'Fuzz Aldrin', None, None, None)
(5, 'Anderson Pooper', None, None, None)
(6, 'Gigabyte', None, None, None)

We can do a comparable operation for the right join.

In [ ]:
result = cursor.execute('''SELECT * FROM
                                cats
                           RIGHT JOIN
                               visits
                           ON
                               cats.cat_id == visits.cat_id''')
for i in result:
    print(i)

(1, 'Megabyte', 1, '02-16-2017', 1)
(1, 'Megabyte', 2, '02-14-2017', 1)
(2, 'Meowly Cyrus', 5, '02-03-2017', 2)
(None, None, 3, '02-0`-2017', 4)

**Question:** The `RIGHT JOIN` command is a recent updated to SQLite. Before this update, how could we perform a right join without it?

What about outer joins?

In [ ]:
# Outer join using pandas
df_cats.merge(df_visits, how = "outer",
              left_on = "cat_id", right_on = "cat_id")

   cat_id             name  visit_id        date
0       1         Megabyte       1.0  02-16-2017
1       1         Megabyte       2.0  02-14-2017
2       2     Meowly Cyrus       5.0  02-03-2017
3       3      Fuzz Aldrin       NaN         NaN
4       4              NaN       3.0  02-0`-2017
5       5  Anderson Pooper       NaN         NaN
6       6         Gigabyte       NaN         NaN

In [ ]:
# Let's do an Outer Join!

result = cursor.execute('''SELECT * FROM cats FULL OUTER JOIN visits
                    ON cats.cat_id == visits.cat_id''')
for i in result:
    print(i)

(1, 'Megabyte', 1, '02-16-2017', 1)
(1, 'Megabyte', 2, '02-14-2017', 1)
(2, 'Meowly Cyrus', 5, '02-03-2017', 2)
(3, 'Fuzz Aldrin', None, None, None)
(5, 'Anderson Pooper', None, None, None)
(6, 'Gigabyte', None, None, None)
(None, None, 3, '02-0`-2017', 4)

## GroupBy and Aggregate in SQL

Let's create a new table to test our groupby's on. This table contains the age, weight, height, and nation id for the country of primary residence.

In [ ]:
# Make a new Table...
cursor.execute('''
CREATE TABLE persons (
    id INTEGER PRIMARY KEY,
    age FLOAT,
    wgt_kg FLOAT,
    hgt_cm FLOAT,
    nat_id INTEGER

)''')

In [ ]:
# Add data to our table
cursor.execute('''INSERT INTO persons VALUES (1, 12.2, 42.3, 145.1, 1)''')
cursor.execute('''INSERT INTO persons VALUES (2, 11.0, 40.8, 143.8, 1)''')
cursor.execute('''INSERT INTO persons VALUES (3, 15.6, 65.3, 165.3, 2)''')
cursor.execute('''INSERT INTO persons VALUES (4, 35.1, 84.2, 185.8, 1)''')
cursor.execute('''INSERT INTO persons VALUES (5, 18.1, 62.2, 176.2, 3)''')
cursor.execute('''INSERT INTO persons VALUES (6, 19.6, 82.1, 180.1, 2)''')
conn.commit()

In [ ]:
# check our table by printing out all rows
ret = cursor.execute('''SELECT * FROM persons''')
for row in ret:
    print(row)

(1, 12.2, 42.3, 145.1, 1)
(2, 11.0, 40.8, 143.8, 1)
(3, 15.6, 65.3, 165.3, 2)
(4, 35.1, 84.2, 185.8, 1)
(5, 18.1, 62.2, 176.2, 3)
(6, 19.6, 82.1, 180.1, 1)

To specify a grouping, we can use the `GROUP BY [column]` command to group by the specified column.

In [ ]:
ret = cursor.execute('''SELECT nat_id, wgt_kg
                        FROM persons
                        GROUP BY nat_id''')
for row in ret:
    print(row)

(1, 42.3)
(2, 65.3)
(3, 62.2)

**Question:** How did SQL aggregate the values by default?

To specifiy the aggregation operation, we have to specify it on the appropriate oclumn in the `SELECT` command. We can also rename it here.

In [ ]:
ret = cursor.execute('''SELECT nat_id, AVG(wgt_kg) as avg_wgt
                        FROM persons
                        GROUP BY nat_id''')
for row in ret:
    print(row)

(1, 62.349999999999994)
(2, 65.3)
(3, 62.2)

### Make sure you close your connection or things go badly!!

- Writes all the changes to the database.

In [ ]:
conn.close()